```
-Arrays:

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the
element type float.

Input Format

A single line of input containing space separated

numbers.

Output Format

Print the reverse NumPy array with type float.

Sample Input

1234-8-10

Sample Output

[-10. -8. 4. 3. 2. 1.]
```

In [ ]:
import numpy

def arrays(arr):
     arr=numpy.array(arr,float)
     reversed_arr=arr[::-1]
     return reversed_arr
     
  


arr = input().strip().split(' ')
result = arrays(arr)
print(result)

```
- Shape and Reshape:

You are given a space separated list of nine integers.
Your task is to convert this list into a 3X3 NumPy
array.

Input Format

A single line of input containing 9 space separated
integers.

Output Format

Print the 3X3 NumPy array.

Sample Input

1 2 3 4 5 6 7 8 9

Sample Output

[[1 2 3]
[4 5 6]
[7 8 9]] 

In [ ]:
import numpy

a=list(map(int,input().split()))
arr=numpy.array(a)
print(numpy.reshape(arr,(3,3)))

-Transpose and Flatten:

You are given a NXM integer array

matrix with space separated elements (
N = rows and M = columns).

Your task is to print the transpose and
flatten results.

Input Format

The first line contains the space
separated values of N and M.

The next N lines contains the space
separated elements of M columns.

Output Format

First, print the transpose array and then
print the flatten.

Sample Input

2 2

1 2

3 4

Sample Output

[[1 3]

 [2 4]]
 
[1 2 3 4]

In [ ]:
import numpy as np 
N,M=map(int,input().split())

arr=[list(map(int,input().split())) for i in range(N)]
np_arr=np.array(arr)
print(np.transpose(np_arr))
print(np_arr.flatten())

```
-Concatenate:

You are given two integer arrays of size
NXP and MXP (N & M are rows, and
P is the column). Your task is to
concatenate the arrays along axis 0.
Input Format
The first line contains space separated
integers N, M and P.
The next N lines contains the space
separated elements of the P columns.
After that, the next M lines contains the
space separated elements of the P
columns.
Output Format
Print the concatenated array of size
(N + M)XP.
Sample Input
4 3 2
1 2
1 2 
1 2
1 2
3 4
3 4
3 4 
Sample Output

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 
 ```

In [ ]:
import numpy as np
N,M,P=map(int,input().split())

A=np.array([list(map(int,input().split())) for i in range(N)])
B=np.array([list(map(int,input().split()))for j in range(M)])

C=np.concatenate((A,B),axis=0)

print(C)



20
[[1]
 [2]]


```
- Zeros and Ones :

You are given the shape of the array in
the form of space-separated integers,
each integer representing the size of
different dimensions, your task is to
print an array of the given shape and
integer type using the tools
numpy.zeros and numpy.ones.
Input Format
A single line containing the space-
separated integers.
Constraints
1 each integer ≤ 3
Output Format
First, print the array using the
numpy.zeros tool and then print the
array with the numpy.ones tool.
Sample Input 0

3 3 3
Sample Output 0

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
  ```

In [ ]:
import numpy as np

my_tuple =tuple(map(int,input().split()))

print(np.zeros(my_tuple,dtype=int))
print(np.ones(my_tuple,dtype=int))

```
- Eye and Identity:

Your task is to print an array of size $$NXM$$ with its
main diagonal elements as 1's and 0's everywhere
else.
Note
In order to get alignment correct, please insert the
line `numpy.set_printoptions(legacy='1.13')`
below the numpy import.
Input Format
A single line containing the space separated values of
N and M.
N denotes the rows.
M denotes the columns.
Output Format
Print the desired NXM array.
Sample Input
```
3 3
```
Sample Output

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
```

In [ ]:
import numpy as np 
np.set_printoptions(legacy='1.13')

n,m=map(int,input().split())
print(np.eye(n,m))

```
-Array Mathematics

You are given two integer arrays, A and B of
dimensions NXM.
Your task is to perform the following operations:
1. Add (A + B)
2. Subtract (A - B)
3. Multiply (A* B)
4. Integer Division (A/B)
5. Mod (A% B)
6. Power (A** B)
Note
There is a method numpy.floor_divide() that works like
numpy.divide() except it performs a floor division.
Input Format
The first line contains two space separated integers,
N and M.
The next N lines contains M space separated
integers of array A.
The following N lines contains M space separated
integers of array B.

Output Format
Print the result of each operation in the given order
under Task.
Sample Input
1 4
1 2 3 4
5 6 7 8
Sample Output
[[6 8 10 12]]
[[-4 -4 -4 -4]]
[[5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[ 1 64 2187 65536]]
```

In [ ]:
import numpy as np

N,M=map(int, input().split())
arr1=[list(map(int,input().split())) for i in range(N)]
arr2=[list(map(int,input().split())) for i in range(N)]

A=np.array(arr1,dtype=int)
B=np.array(arr2,dtype=int)

print(np.add(A,B))
print(np.subtract(A,B))
print(np.multiply(A,B))
print(np.floor_divide(A,B))
print(np.mod(A,B))
print(np.power(A,B))


int64
[2 4 6]


```
-Floor, Ceil and Rint:

Task

You are given a 1-D array, A. Your task is to print the
floor, ceil and rint of all the elements of A.
Note
In order to get the correct output format, add the line
numpy.set_printoptions(legacy='1.13') below the
numpy import.
Input Format
A single line of input containing the space separated
elements of array A.
Output Format
On the first line, print the floor of A.
On the second line, print the ceil of A.
On the third line, print the rint of A.
Sample Input
1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
Sample Output
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]
```

In [ ]:
import numpy as np 
np.set_printoptions(legacy='1.13')
A=np.array(list(map(float,input().split())))

print(np.floor(A))
print(np.ceil(A))
print(np.rint(A))

```
-sum and prod:

You are given a 2-D array with dimensions NXM.
Your task is to perform the sum tool over axis 0 and
then find the product of that result.
Input Format
The first line of input contains space separated values
of N and M.
The next NV lines contains M space separated
integers.
Output Format
Compute the sum along axis 0. Then, print the
product of that sum.
Sample Input
2 2
1 2
3 4
Sample Output
24
```

In [ ]:
import numpy as np 

N,M=map(int, input().split())
A=np.array([list(map(int,input().split())) for i in range(N)])
s=np.sum(A,axis=0)

print(np.prod(s))

```
-Min and Max:

You are given a 2-D array with dimensions NXM.
Your task is to perform the min function over axis 1
and then find the max of that.
Input Format
The first line of input contains the space separated
values of N and M.
The next N lines contains M space separated
integers.
Output Format
Compute the min along axis 1 and then print the max
of that result.
Sample Input
42
2 5
3 7
1 3
4 0
Sample Output
3
```

In [ ]:
import numpy as np
N,M=map(int,input().split())
A=np.array([list(map(int,input().split())) for i in range(N)])
mini=np.min(A,axis=1)
print(np.max(mini))

```
-Mean, Var, and Std:

You are given a 2-D array of size NXM.
Your task is to find:
1. The mean along axis 1
2. The var along axis 0
3. The std along axis $$None$$

Input Format
The first line contains the space separated values of
N and M.
The next N lines contains M space separated
integers.

Output Format
First, print the mean.
Second, print the var.
Third, print the std.

Sample Input

2 2
1 2
3 4


Sample Output
[ 1.5  3.5]
[ 1.  1.]
1.11803398875
```

In [ ]:
import numpy as np

N,M=map(int,input().split())
A=np.array([list(map(int,input().split())) for i in range(N)])
print(np.mean(A,axis=1))
print(np.var(A,axis=0))
if(np.std(A)==0):
    print(0.0)
else:
    print(f"{np.std(A):.11f}")

```
- Dot and Cross:

You are given two arrays A and B. Both have
dimensions of NXN.
Your task is to compute their matrix product.
Input Format
The first line contains the integer N.
The next N lines contains N space separated
integers of array A.
The following N lines contains N space separated
integers of array B.
Output Format
Print the matrix multiplication of A and B.
Sample Input
2
1 2
3 4
1 2
3 4
Sample Output
[[ 7 10]
 [15 22]]
```

In [ ]:
import numpy as np
N=int(input())
A=np.array([list(map(int,input().split())) for i in range(N)])
B=np.array([list(map(int,input().split())) for i in range(N)])
print(np.matmul(A,B))

```
-Inner and Outer

You are given two arrays: A and B.
Your task is to compute their inner and outer product.
Input Format
The first line contains the space separated elements
of array A.
The second line contains the space separated
elements of array B.
Output Format
First, print the inner product.
Second, print the outer product.
Sample Input
0 1
2 3
Sample Output
3
[[0 0]
[2 3]]
```

In [ ]:
import numpy as np

A=np.array(list(map(int,input().split())))
B=np.array(list(map(int,input().split())))

print(np.inner(A,B))
print(np.outer(A,B))

```
-Polynomials

You are given the coefficients of a polynomial P.
Your task is to find the value of P at point x.
Input Format
The first line contains the space separated value of
the coefficients in P.
The second line contains the value of x.
Output Format
Print the desired value.
Sample Input
1.1 2 3
0
Sample Output
3.0
```

In [ ]:
import numpy as np

poly=[float(x) for x in input().split()]
x=float(input())
print(np.polyval(poly,x))

```

-Linear Algebra

You are given a square matrix A with dimensions NVX
N. Your task is to find the determinant. Note: Round
the answer to 2 places after the decimal.
Input Format
The first line contains the integer N.
The next N lines contains the N space separated
elements of array A.
Output Format
Print the determinant of A.
Sample Input
2
1.1 1.1
1.1 1.1
Sample Output
0.0

```

In [ ]:
import numpy as np
np.set_printoptions(legacy='1.13')

N=int(input())
A=np.array([list(map(float,input().split())) for i in range(N)])
print(np.linalg.det(A))